_target_: jejeqx._src.datamodules.coords.AlongTrackDM
paths: "/gpfswork/rech/yrf/commun/data_challenges/dc20a_osse/test/dc_ref/NATL60-CJM165_GULFSTREAM*"
batch_size: 10000
spatial_coords: ["lat", "lon"]
temporal_coords: ["time"]
variables: ["sossheig"]
evaluation: True
coarsen:
    lon: 2
    lat: 2
resample: "1D"
select:
    time: {_target_: builtins.slice, _args_: ["2012-10-01", "2013-10-01"]}
