config: "/gpfswork/rech/cli/uvo53rl/checkpoints/nerfs/siren/swot1nadir5/train_more/config.pkl"
checkpoint: "/gpfswork/rech/cli/uvo53rl/checkpoints/nerfs/siren/swot1nadir5/train_more/checkpoint_model.ckpt"
