# @package _global_

defaults:
    - _self_
    - data: nadir.yaml
    - model: siren.yaml
    - optimizer: adam.yaml
    - spatial_transforms: default.yaml
    - temporal_transforms: default.yaml
    - evaluation: natl60_lores.yaml
    - logger: wandb_jz.yaml
    - pretrained: siren_nadir.yaml
    - results: default.yaml
    
    
num_epochs: 100
stage: "train"
dataset: null