alongrack:
    _target_: jejeqx._src.datamodules.coords_v2.AlongTrackDM
    paths: "/gpfswork/rech/yrf/commun/data_challenges/dc20a_osse/staging/ml_ready/nadir4.nc"
    batch_size: 32
    shuffle: True
    train_size: 0.80
    spatial_coords: ["lat", "lon"]
    temporal_coords: ["time"]
    variables: ["ssh"]
    evaluation: False
    decode_times: True
    spatial_units: "degrees"
    time_unit: "seconds"
    time_freq: 1
    t0: "2012-10-01"
    select: 
        time: {_target_: builtins.slice, _args_: ["2012-10-01", "2012-12-02"]}
        
gridded:
    _target_: jejeqx._src.datamodules.coords_v2.AlongTrackDM
    paths: "/gpfswork/rech/cli/uvo53rl/projects/jejeqx/data/natl60/dataset_nadir_0d.nc"
    batch_size: 32
    shuffle: True
    train_size: 0.80
    spatial_coords: ["lat", "lon"]
    temporal_coords: ["time"]
    variables: ["ssh_mod"]
    evaluation: False
    decode_times: True
    spatial_units: "degrees"
    time_unit: "seconds"
    time_freq: 1
    t0: "2012-10-01"
    select: 
        time: {_target_: builtins.slice, _args_: ["2012-10-01", "2012-12-02"]}
        
        
        
alongtrack_scaled:
    _target_: jejeqx._src.datamodules.coords_v2.AlongTrackDM
    paths: "/gpfswork/rech/yrf/commun/data_challenges/dc20a_osse/staging/ml_ready/nadir4.nc"
    batch_size: 32
    shuffle: True
    train_size: 0.80
    spatial_coords: ["lat", "lon"]
    temporal_coords: ["time"]
    variables: ["ssh"]
    evaluation: False
    decode_times: True
    spatial_units: "degrees"
    time_unit: "seconds"
    time_freq: 1
    t0: "2012-10-01"
    select: 
        time: {_target_: builtins.slice, _args_: ["2012-10-01", "2012-12-02"]}
        
    temporal_transform: ${temporal_transforms}
    spatial_transform: ${spatial_transforms}
    
    
gridded_scaled:
    _target_: jejeqx._src.datamodules.coords_v2.AlongTrackDM
    paths: "/gpfswork/rech/cli/uvo53rl/projects/jejeqx/data/natl60/dataset_nadir_0d.nc"
    batch_size: 32
    shuffle: True
    train_size: 0.80
    spatial_coords: ["lat", "lon"]
    temporal_coords: ["time"]
    variables: ["ssh_mod"]
    evaluation: False
    decode_times: True
    spatial_units: "degrees"
    time_unit: "seconds"
    time_freq: 1
    t0: "2012-10-01"
    select: 
        time: {_target_: builtins.slice, _args_: ["2012-10-01", "2012-12-02"]}
        
    temporal_transform: ${temporal_transforms}
    spatial_transform: ${spatial_transforms}


spatial_transforms: 
    _target_: jejeqx._src.transforms.pipelines.make_pipeline
    _recursive_: False
    steps_config:
        - spatialminmax:
            _target_: jejeqx._src.transforms.dataframe.scaling.MinMaxDF
            columns: ["lat", "lon"]
            min_val: -1
            max_val: 1
                 
temporal_transforms: 
    _target_: jejeqx._src.transforms.pipelines.make_pipeline
    _recursive_: False
    steps_config:
        - timeminmax:
            _target_: jejeqx._src.transforms.dataframe.scaling.MinMaxDF
            columns: ["time"]
            min_val: -1
            max_val: 1

natl60_dc20a_eval:
    _target_: "jejeqx._src.datamodules.coords_v2.EvalCoordDM"
    paths: "/gpfswork/rech/cli/uvo53rl/projects/jejeqx/data/natl60/NATL60-CJM165_GULFSTREAM_ssh_y2013.1y.nc"
    batch_size: 10_000
    shuffle: False
    train_size: 0.80
    decode_times: False
    evaluation: True
    spatial_coords: ["lat", "lon"]
    temporal_coords: ["time"]
    variables: ["ssh"]
    resample: "1D"
    spatial_units: "degrees"
    time_unit: "seconds"
    time_freq: 1
    t0: "2012-10-01"
    select: 
        time: {_target_: builtins.slice, _args_: ["2012-10-01", "2012-12-02"]}