_target_: jejeqx._src.nets.nerfs.base.NerF

basis_net:
    _target_: equinox.nn.MLP
    in_size: 4
    out_size: 1
    width_size: 256
    depth: 5
    activation:
        _target_: "jejeqx._src.nets.activations.ReLU"
    final_activation:
        _target_: "equinox.nn.Identity"
    key:
        _target_: jax.random.PRNGKey
        seed: 123
network:
    _target_: equinox.nn.Identity
